"""empty message

Revision ID: 215c3cc7fda3
Revises: ec6cf537c7db
Create Date: 2024-02-26 18:20:30.784252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '215c3cc7fda3'
down_revision = 'ec6cf537c7db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'change_state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('change_state', sa.VARCHAR(length=50), nullable=True))
    # ### end Alembic commands ###
