"""empty message

Revision ID: 5cfaf8ce45d7
Revises: a29c2103fe3f
Create Date: 2024-06-27 14:24:49.195612

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cfaf8ce45d7'
down_revision = 'a29c2103fe3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connect_statements', sa.Column('messages', sa.LargeBinary(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('connect_statements', 'messages')
    # ### end Alembic commands ###
