"""empty message

Revision ID: a29c2103fe3f
Revises: 134df8d6691b
Create Date: 2024-06-26 01:26:04.389110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a29c2103fe3f'
down_revision = '134df8d6691b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connect_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=30), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('for_whom', sa.String(length=30), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connect_statements')
    # ### end Alembic commands ###
