"""empty message

Revision ID: b124f19cca3e
Revises: 
Create Date: 2024-08-30 23:31:58.761242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b124f19cca3e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('host_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('icmp_params',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ping_interval', sa.Integer(), nullable=True),
    sa.Column('icmp_count', sa.Integer(), nullable=True),
    sa.Column('icmp_interval', sa.Integer(), nullable=True),
    sa.Column('ping_workers', sa.Integer(), nullable=True),
    sa.Column('icmp_timeout', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('login', sa.String(length=30), nullable=True),
    sa.Column('passw', sa.String(length=30), nullable=True),
    sa.Column('privilege', sa.String(length=20), nullable=True),
    sa.Column('carbon_login', sa.String(length=30), nullable=True),
    sa.Column('carbon_passw', sa.String(length=30), nullable=True),
    sa.Column('user_data', sa.Text(), nullable=True),
    sa.Column('last_visit', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('login')
    )
    op.create_table('hosts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('state', sa.String(length=20), nullable=True),
    sa.Column('change_state', sa.String(length=50), nullable=True),
    sa.Column('checking', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['folder_id'], ['host_folders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hosts')
    op.drop_table('users')
    op.drop_table('icmp_params')
    op.drop_table('host_folders')
    # ### end Alembic commands ###
