"""empty message

Revision ID: dccc91cd0583
Revises: 215c3cc7fda3
Create Date: 2024-02-26 19:10:52.879705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccc91cd0583'
down_revision = '215c3cc7fda3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hosts', sa.Column('change_state', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hosts', 'change_state')
    # ### end Alembic commands ###
