"""empty message

Revision ID: ec6cf537c7db
Revises: 1f0590ae1ab7
Create Date: 2024-02-26 18:14:17.162911

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec6cf537c7db'
down_revision = '1f0590ae1ab7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nas_dumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('dump', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sw_dumps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Integer(), nullable=True),
    sa.Column('dump', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('hosts', 'change_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosts', 'change_state',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_table('sw_dumps')
    op.drop_table('nas_dumps')
    # ### end Alembic commands ###
