"""empty message

Revision ID: eec1dbbecf1b
Revises: 715f79abbd75
Create Date: 2024-02-19 23:25:21.731938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eec1dbbecf1b'
down_revision = '715f79abbd75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gpon_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('vlan', sa.Integer(), nullable=True),
    sa.Column('gemport', sa.Integer(), nullable=True),
    sa.Column('srv_profile', sa.Integer(), nullable=True),
    sa.Column('line_profile', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('hosts', 'change_state',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('hosts', 'change_state',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True)
    op.drop_table('gpon_profiles')
    # ### end Alembic commands ###
